# Practical Application III: Comparing Classifiers

**Overview**: In this practical application, your goal is to compare the performance of the classifiers we encountered in this section, namely K Nearest Neighbor, Logistic Regression, Decision Trees, and Support Vector Machines.  We will utilize a dataset related to marketing bank products over the telephone.

### Getting Started

Our dataset comes from the UCI Machine Learning repository [link](https://archive.ics.uci.edu/ml/datasets/bank+marketing).  The data is from a Portugese banking institution and is a collection of the results of multiple marketing campaigns.  We will make use of the article accompanying the dataset [here](CRISP-DM-BANK.pdf) for more information on the data and features.

### Problem 1: Understanding the Data

To gain a better understanding of the data, please read the information provided in the UCI link above, and examine the **Materials and Methods** section of the paper.  How many marketing campaigns does this data represent?

* This data represents 17 marketing campaigns that occured between May 2008 and November 2010.

### Problem 2: Read in the Data

Use pandas to read in the dataset `bank-additional-full.csv` and assign to a meaningful variable name.

In [1]:
import pandas as pd

In [2]:
bank = pd.read_csv('data/bank-additional-full.csv', sep = ';')

In [3]:
bank.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [4]:
bank.shape

(41188, 21)

### Problem 3: Understanding the Features


Examine the data description below, and determine if any of the features are missing values or need to be coerced to a different data type.


```
Input variables:
# bank client data:
1 - age (numeric)
2 - job : type of job (categorical: 'admin.','blue-collar','entrepreneur','housemaid','management','retired','self-employed','services','student','technician','unemployed','unknown')
3 - marital : marital status (categorical: 'divorced','married','single','unknown'; note: 'divorced' means divorced or widowed)
4 - education (categorical: 'basic.4y','basic.6y','basic.9y','high.school','illiterate','professional.course','university.degree','unknown')
5 - default: has credit in default? (categorical: 'no','yes','unknown')
6 - housing: has housing loan? (categorical: 'no','yes','unknown')
7 - loan: has personal loan? (categorical: 'no','yes','unknown')
# related with the last contact of the current campaign:
8 - contact: contact communication type (categorical: 'cellular','telephone')
9 - month: last contact month of year (categorical: 'jan', 'feb', 'mar', ..., 'nov', 'dec')
10 - day_of_week: last contact day of the week (categorical: 'mon','tue','wed','thu','fri')
11 - duration: last contact duration, in seconds (numeric). Important note: this attribute highly affects the output target (e.g., if duration=0 then y='no'). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model.
# other attributes:
12 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)
13 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted)
14 - previous: number of contacts performed before this campaign and for this client (numeric)
15 - poutcome: outcome of the previous marketing campaign (categorical: 'failure','nonexistent','success')
# social and economic context attributes
16 - emp.var.rate: employment variation rate - quarterly indicator (numeric)
17 - cons.price.idx: consumer price index - monthly indicator (numeric)
18 - cons.conf.idx: consumer confidence index - monthly indicator (numeric)
19 - euribor3m: euribor 3 month rate - daily indicator (numeric)
20 - nr.employed: number of employees - quarterly indicator (numeric)

Output variable (desired target):
21 - y - has the client subscribed a term deposit? (binary: 'yes','no')
```

In [13]:
# Identifying missing values
bank.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

* There are no missing values in any feature. No features need to be coerced to a different data type. One-hot encoding would be an appropriate technique to transform categorical features into numerical values for machine learning.

### Problem 4: Understanding the Task

After examining the description and data, your goal now is to clearly state the *Business Objective* of the task.  State the objective below.

In [15]:
bank.info()

<class 'pandas.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  str
 2   marital         41188 non-null  str
 3   education       41188 non-null  str
 4   default         41188 non-null  str
 5   housing         41188 non-null  str
 6   loan            41188 non-null  str
 7   contact         41188 non-null  str
 8   month           41188 non-null  str
 9   day_of_week     41188 non-null  str
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  str
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  str
dtypes: float64(5), int64(5), str(11)
memory usage: 9.1 MB

* The business objective is to create a model that predicts whether a client will subscribe to a term deposit and identifies which characteristics influence the client's decision, in order to optimize the success of marketing campaigns.

### Problem 5: Engineering Features

Now that you understand your business objective, we will build a basic model to get started.  Before we can do this, we must work to encode the data.  Using just the bank information features, prepare the features and target column for modeling with appropriate encoding and transformations.

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [17]:
X = bank.drop('y', axis = 1)
y = bank['y']

In [18]:
preprocessor = ColumnTransformer([
    ('encode', OneHotEncoder(), X.select_dtypes('str').columns),
    ('scale', StandardScaler(), X.select_dtypes(['int64','float64']).columns)
])

### Problem 6: Train/Test Split

With your data prepared, split it into a train and test set.

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=42)

In [21]:
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

### Problem 7: A Baseline Model

Before we build our first model, we want to establish a baseline.  What is the baseline performance that our classifier should aim to beat?

In [27]:
float(round((bank['y'] == 'yes').sum() / len(bank['y']) * 100, 2))

11.27

### Problem 8: A Simple Model

Use Logistic Regression to build a basic model on your data.

In [29]:
from sklearn.linear_model import LogisticRegression

lgr = LogisticRegression()

lgr.fit(X_train_transformed, y_train)

LogisticRegression()

### Problem 9: Score the Model

What is the accuracy of your model?

In [32]:
accuracy = lgr.score(X_test_transformed, y_test)
accuracy

0.9151209090026221

### Problem 10: Model Comparisons

Now, we aim to compare the performance of the Logistic Regression model to our KNN algorithm, Decision Tree, and SVM models.  Using the default settings for each of the models, fit and score each.  Also, be sure to compare the fit time of each of the models.  Present your findings in a `DataFrame` similar to that below:

| Model | Train Time | Train Accuracy | Test Accuracy |
| ----- | ---------- | -------------  | -----------   |
|     |    |.     |.     |

In [34]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
import time

In [35]:
model_comparison = {
    'models' : [LogisticRegression(), KNeighborsClassifier(), DecisionTreeClassifier(), SVC()],
    'train_time' : [],
    'train_accuracy' : [],
    'test_accuracy' : []
}

for model in model_comparison['models']:
    start = time.time()
    classifier = model.fit(X_train_transformed, y_train)
    model_comparison['train_time'].append(time.time() - start)
    model_comparison['train_accuracy'].append(classifier.score(X_train_transformed, y_train))
    model_comparison['test_accuracy'].append(classifier.score(X_test_transformed, y_test))

In [39]:
model_comparison_df = pd.DataFrame(model_comparison)
model_comparison_df

                     models  train_time  train_accuracy  test_accuracy
0      LogisticRegression()    0.218663        0.910233       0.915121
1    KNeighborsClassifier()    0.039161        0.927649       0.905409
2  DecisionTreeClassifier()    0.176241        1.000000       0.890356
3                     SVC()   11.834365        0.922307       0.913664

### Problem 11: Improving the Model

Now that we have some basic models on the board, we want to try to improve these.  Below, we list a few things to explore in this pursuit.


- Hyperparameter tuning and grid search.  All of our models have additional hyperparameters to tune and explore.  For example the number of neighbors in KNN or the maximum depth of a Decision Tree.  
- Adjust your performance metric

In [41]:
from sklearn.model_selection import GridSearchCV

In [55]:
model_comparison_grid = {
    'models' : [LogisticRegression(), KNeighborsClassifier(), DecisionTreeClassifier(), SVC()],
    'train_time' : [],
    'train_roc' : [],
    'test_roc' : []
}

In [56]:
param_grid = [
    {},  # lgr
    {'n_neighbors': [3, 5, 7, 9, 11]},  # knn
    {'max_depth': [None, 5, 10, 20], 'min_samples_split': [2, 5, 10]},  # dtee
    {'C': [0.1, 1, 10], 'kernel': ['linear', 'rbf']}  # svc
]

In [57]:
for model, params in zip(model_comparison_grid['models'], param_grid):
    grid = GridSearchCV(
        estimator=model,
        param_grid=params,
        scoring='roc_auc',
        cv=3
    )

    start = time.time()
    grid.fit(X_train_transformed, y_train)

    model_comparison_grid['train_time'].append(time.time() - start)
    model_comparison_grid['train_roc'].append(
        grid.score(X_train_transformed, y_train)
    )
    model_comparison_grid['test_roc'].append(
        grid.score(X_test_transformed, y_test)
    )

In [58]:
model_comparison_grid_df = pd.DataFrame(model_comparison_grid)
model_comparison_grid_df

                     models  train_time  train_roc  test_roc
0      LogisticRegression()    0.775534   0.934691  0.942253
1    KNeighborsClassifier()    3.937154   0.951845  0.911675
2  DecisionTreeClassifier()    4.135300   0.928968  0.933621
3                     SVC()  372.866719   0.932656  0.939401

##### Questions